# Generated by Django 4.2.20 on 2025-04-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijaTalk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='breaking_news',
            field=models.BooleanField(default=False),
        ),
    ]
