# Generated by Django 4.2.20 on 2025-04-28 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('naijaTalk', '0002_newsarticle_breaking_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
