# Generated by Django 4.2.20 on 2025-04-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijaTalk', '0003_newsarticle_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image_url_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='image_url_3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
