# Generated by Django 4.2.20 on 2025-05-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijaTalk', '0004_newsarticle_image_url_2_newsarticle_image_url_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='local_news',
            field=models.BooleanField(default=False),
        ),
    ]
