# Generated by Django 4.2.20 on 2025-05-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijaTalk', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='last_fetched',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
