# Generated by Django 4.2.20 on 2025-05-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijaTalk', '0008_newscategory_last_fetched_alter_newscategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='published_date',
            field=models.DateTimeField(),
        ),
    ]
